version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vikas123
      POSTGRES_DB: Recordss
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: interviewtask-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:vikas123@postgres:5432/Recordss
    ports:
      - "3001:3001"

  frontend:
    image: interviewtask-frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080" # Map port 8080 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
